# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 100

  - name: Skills
    url: /#papers
    weight: 200

  - name: Projects
    url: /#talks
    weight: 300
  - parent: Projects
    name: Personal
    url: /#talks
    weight: 310
  - parent: Projects
    name: Team
    url: /#talks
    weight: 320

  - name: Activities
    url: /#news
    weight: 400
  - parent: Activities
    name: Academic Courses
    url: /#experience/
    weight: 410
  - parent: Activities
    name: Extracurricular
    url: /#experience/
    weight: 420

  - name: Contact
    url: /
    weight: 500


  # - name: Projects
  #   url: projects/
  #   weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
